import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/switch-theme";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { getSession } from "@/lib/utils/get-session";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(await getSession());
  return (
    <html lang="en" suppressHydrationWarning className={inter.className}>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <div className="fixed -top-10 h-30 w-full md:top-0 lg:h-20">
            <Image
              src={wave}
              alt="Kanban Method"
              fill
              className="object-cover"
            />
          </div> */}
          {/* <div className="w-full px-4"> */}
          <div className="fixed top-2 right-5 z-30">
            <ModeToggle />
          </div>

          <NuqsAdapter>{children}</NuqsAdapter>
          {/* </div> */}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
