import type { Metadata } from "next";
import "./globals.css";
import wave from "@/public/wave-hero.svg";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/switch-theme";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.className}>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed -top-10 h-30 w-full md:top-0 lg:h-20">
            <Image
              src={wave}
              alt="Kanban Method"
              fill
              className="object-cover"
            />
          </div>
          <div className="px-4">
            <div className="fixed top-2 right-4 z-20">
              <ModeToggle />
            </div>

            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
